on:
  workflow_dispatch:
  push:

env:
  pa5: ${{ secrets.pa5 }}

jobs:

  build:
    strategy:
      matrix:
        arch: [x86, x64]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@user-action


      - uses: li5ht4ay-3es/ac5io4s@checkout-repo
        with:
          token: "${{ env.pa5 }}"


      - uses: li5ht4ay-3es/Sa5eB4y@tools-install


      - uses: li5ht4ay-3es/ac5io4s@mingw-install
        with:
          arch: ${{ matrix.arch }}


      - uses: li5ht4ay-3es/ac5io4s@cache-read
        with:
          name: cache-${{ matrix.arch }}


      - run: |
          git merge origin/compiler-flags
          git merge origin/libretro-options

          git merge origin/crop-border
          git merge origin/fast-bootrom
          git merge origin/osd-message
          git merge origin/sprite-limit
          git merge origin/video-overclock
          git merge origin/volume-level


      - working-directory: libretro
        run: |
          make platform="win" CC="$MINGW_CC" CXX="$MINGW_CXX"


      - uses: li5ht4ay-3es/ac5io4s@cache-write
        with:
          name: cache-${{ matrix.arch }}


      - uses: actions/upload-artifact@main
        with:
          name: SameBoy_${{ matrix.arch }}
          path: build/bin
